steps:
  # Step 1: Compile the Go Application
  - name: 'gcr.io/cloud-builders/go'
    env:
      - 'GOPATH=/gopath'
    args:
      - 'build'
      - '-o'
      - 'main'
      - 'main.go'

  # Step 2: Build the Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/qwiklabs-gcp-02-ea79d2368929/my-repository-eu/hello-cloudbuild-dev:v2.0'
      - '.'

  # Step 3: Push the Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/qwiklabs-gcp-02-ea79d2368929/my-repository-eu/hello-cloudbuild-dev:v2.0'

  # Step 4: Deploy to DEV Namespace
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy'
    args:
      - '-n'
      - 'dev'
      - 'apply'
      - '-f'
      - 'dev/deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'

options:
  logging: CLOUD_LOGGING_ONLY
